forward_position_controller_test_publisher:
  ros__parameters:

    timer_period: 1

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6", "pos7"]
    pos1: [-2.25, -0.39,  1.30,  0.05,  3.10,  1.25,  1.00,  1.00]
    pos2: [-0.35, -0.25,  1.15, -2.15,  1.80, -1.20,  0.00,  0.00]
    pos3: [ 1.40,  0.39,  0.95,  2.30,  2.65, -0.60,  0.60,  0.60]
    pos4: [-2.35,  0.32, -1.10, -1.50,  1.40,  0.50,  0.00,  0.00]
    pos5: [-0.80, -0.28,  0.70,  0.00,  2.10, -0.15,  0.50,  0.50]
    pos6: [-0.17,  0.37, -1.13, -1.14,  0.95,  1.09,  1.15,  1.15]
    pos7: [ 0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00]


joint_trajectory_controller_test_publisher:
  ros__parameters:

    timer_period: 6.0
    motion_duration: 4.0

    goal_names: ["pos1", "pos2", "pos3", "pos4", "pos5", "pos6", "pos7"]
    pos1: [-2.25, -0.39,  1.30,  0.05,  3.10,  1.25,  1.00,  1.00]
    pos2: [-0.35, -0.25,  1.15, -2.15,  1.80, -1.20,  0.00,  0.00]
    pos3: [ 1.40,  0.39,  0.95,  2.30,  2.65, -0.60,  0.60,  0.60]
    pos4: [-2.35,  0.32, -1.10, -1.50,  1.40,  0.50,  0.00,  0.00]
    pos5: [-0.80, -0.28,  0.70,  0.00,  2.10, -0.15,  0.50,  0.50]
    pos6: [-0.17,  0.37, -1.13, -1.14,  0.95,  1.09,  1.15,  1.15]
    pos7: [ 0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00,  0.00]

    joints:
      - shoulder_joint
      - upper_arm_joint
      - elbow_joint
      - forearm_joint
      - wrist_joint
      - hand_joint
      - finger_joint
      - opposite_finger_joint

    # Refuse to start sending trajectories if robot is not
    # in the defined initial position
    check_initial_position: false
    initial_position_limits:
      shoulder_joint:  [-0.01, 0.01]
      upper_arm_joint: [-0.01, 0.01]
      elbow_joint:     [-0.01, 0.01]
      forearm_joint:   [-0.01, 0.01]
      wrist_joint:     [-0.01, 0.01]
      hand_joint:      [-0.01, 0.01]
      finger_joint:    [-0.01, 0.01]
      opposite_finger_joint:    [-0.01, 0.01]
